### DISCUSSION TITLE
10.0: Create an interactive map of Europe

### DISCUSSION THREAD

**Discussion by jstanden** [cerb/cerb-release#11] [Guides and Tutorials]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/63288/113072000-c6116b00-917a-11eb-9daf-efd499fc8fc3.png">

# Introduction

You can use [Maps KATA](https://cerb.ai/docs/maps/) in Cerb 10 to quickly build interactive maps for any combination of regions in the world.

In this example we'll use filters to build a map of European countries from the baseline world map.

# Create a workspace

We'll create a temporary workspace for our map.

Optionally, you can skip adding a new page or new tab and add a widget to one of your existing workspaces.

## Add a workspace page

Click the down arrow in the pages menu.

  ![image](https://user-images.githubusercontent.com/63288/113070444-68c7ea80-9177-11eb-80f5-b0ab7d279fcf.png)

Click the **(+)** icon in the top right of the worklist.

  ![image](https://user-images.githubusercontent.com/63288/113070527-9ca31000-9177-11eb-9f85-e84eafeeba5a.png)

Set **Owner:** to **Me**.

In the **Library** tab, select **Empty Workspace**.

Name it `Maps`.

Click the **Create** button.

Click on the **Maps** link in the worklist.

## Add a workspace tab

Click on the **Add** button.

In the **Library** tab, select **Dashboard**.

Set **Name:** to `Europe`.

Click the **Create** button.

## Add a map widget

Click the **Add Widget** button.

In the **Library** tab, select **World Countries**.

Click the **Create** button.

# Modify the map

Click on the **Map: World Countries** title above the widget and select **Edit** from the menu.

Rename the widget **Europe**.

## Filter the countries by continent

In `maps:regions:` add a `filter:` option like:

```yaml
  regions:
    filter:
      property: continent
      is: Europe
```

Click the **Save & Continue** button. The map should now only show European countries.

Click the minimize button in the popup so it temporarily no longer obscures the map:

  ![image](https://user-images.githubusercontent.com/63288/113070960-9b261780-9178-11eb-9a1a-c60f8c91de2b.png)

We need to center and zoom on Europe so we can find the right location and scale.

Click on a land mass (like Russia) and drag Europe toward the center of the widget.

Use the mouse wheel to zoom in, until you have something like:

  <img width="1384" alt="image" src="https://user-images.githubusercontent.com/63288/113071152-07088000-9179-11eb-8aaf-71e31a5ab091.png">

Make a note of the coordinates in the lower right of the map:

  ![image](https://user-images.githubusercontent.com/63288/113071272-3d45ff80-9179-11eb-8395-7d1ee16377a2.png)

At the top of the browser, click the maximize icon to restore the popup:

![image](https://user-images.githubusercontent.com/63288/113071300-4c2cb200-9179-11eb-8bd7-390c620d263a.png)

In `map:projection:`, set the `scale:` and `center:` attributes using the current map values.

```yaml
  projection:
    type: mercator
    scale: 244
    center:
      longitude: 43.4518
      latitude: 55.6166
```

Click the **Save & Continue** button.

### Filter the points by continent

Scroll down to `map:points:`. Add another `filter:` like:

```yaml
  points:
    resource:
      uri: cerb:resource:mapPoints.worldCapitalCities
    filter:
      property: continent
      is: Europe
```

Click the **Save Changes** button.

The capital cities should now be properly filtered so none are outside of Europe.

  <img width="1381" alt="image" src="https://user-images.githubusercontent.com/63288/113071659-13410d00-917a-11eb-8061-3b89a368965a.png">

### Test resetting the map

Pan and zoom a bit.

When you click the reset button in the map controls it should return to your new defaults.

  ![image](https://user-images.githubusercontent.com/63288/113071710-2c49be00-917a-11eb-8c88-868416920817.png)

# Reference

For reference, here is the fully modified map KATA:

```yaml
map:
  resource:
    uri: cerb:resource:map.world.countries
  projection:
    type: mercator
    scale: 244
    center:
      longitude: 43.4518
      latitude: 55.6166
  regions:
    filter:
      property: continent
      is: Europe
    label:
      title: name
      properties:
        name:
          label: Country
        pop_est:
          label: Population
          format: number
        lastcensus:
          label: Last Census
    fill:
      choropleth:
        property: pop_est
        classes: 8
  points:
    resource:
      uri: cerb:resource:mapPoints.worldCapitalCities
    filter:
      property: continent
      is: Europe
    label:
      title: name
      properties:
        adm0name:
          label: Country
    size:
      default: 2
    fill:
      default: #646464
```
