### DISCUSSION TITLE
10.0: Add a 'move' interaction to ticket profiles and cards

### DISCUSSION THREAD

**Discussion by jstanden** [cerb/cerb-release#13] [Guides and Tutorials]
https://user-images.githubusercontent.com/63288/114757004-31794200-9d10-11eb-866f-b20751a42499.mov

# Introduction

One of the most common actions on ticket records is moving them to another group and/or bucket.

While you can edit a ticket record to change its group and bucket, the editor can be overwhelming for new team members, and it doesn't offer much customization.

With [interactions](https://cerb.ai/docs/interactions/) in Cerb 10 you can create a shortcut for moving tickets right on card popups and profile pages.

You can also completely customize how it works. For instance, some teams prefer to sort buckets in an order other than alphabetical (e.g. most frequently used).

The **cerb.ticket.move** interaction is included with Cerb 10+, so you don't need to import anything to use it.

# Adding the move interaction to ticket profiles

If you want to add a 'Move' shortcut to ticket profiles, navigate to any ticket profile page as an administrator.

Click on the gear icon to the right of the toolbar at the top of the profile:

  ![image](https://user-images.githubusercontent.com/63288/114645023-81fb8b80-9c8d-11eb-8532-6495317a4e93.png)

Paste the following [toolbar](https://cerb.ai/docs/toolbars/) [KATA](https://cerb.ai/docs/kata/):

```yaml
interaction/ticketMove:
  label: Move
  uri: cerb:automation:cerb.ticket.move
  icon: inbox-out
  hidden@bool: {{record__type is not record type ('ticket')}}
  inputs:
    ticket: {{record_id}}
  after:
    refresh_widgets@list:
      Actions
      Status
      Ticket
```

This does a lot of work for us:

* It creates an interaction button with the label **Move**.
* It runs the `cerb.ticket.move` automation when that button is clicked. 
* It uses the icon of an inbox with an outgoing arrow. 
* The button is hidden unless the profile is for a ticket record. 
* A `ticket:` input is passed to the automation using the current record's ID.
* After the interaction finishes, we refresh three widgets by name on the profile page. This avoids refreshing the entire page, so the interaction can be used even while the reply editor is open.

Click the **Save Changes** button.

You should now see a new **Move** button in the toolbar:

  <img width="516" alt="image" src="https://user-images.githubusercontent.com/63288/114645150-b5d6b100-9c8d-11eb-97f3-59f333500ba2.png">

# Adding the move interaction to ticket cards

If you want to add the move shortcut to ticket cards, the process is very similar to the above.

Open any ticket card popup as an administrator.

Click on the gear icon to the right of the top toolbar:

  ![image](https://user-images.githubusercontent.com/63288/114645575-968c5380-9c8e-11eb-91ae-8272a82e688c.png)

Paste the following toolbar KATA:

```yaml
interaction/ticketMove:
  label: Move
  uri: cerb:automation:cerb.ticket.move
  icon: inbox-out
  hidden@bool: {{record__type is not record type ('ticket')}}
  inputs:
    ticket: {{record_id}}
  after:
    refresh_widgets@list:
      Properties
```

Click the **Save Changes** button.

# Adding the move interaction to ticket card widgets

You can also add the same interaction to an interactions toolbar on a ticket card popup. This is useful when you don't want the top toolbar to be too cluttered with infrequently used interactions.

Open the card popup for any ticket as an administrator.

Click the **Add Widget** button at the bottom of the popup.

  ![image](https://user-images.githubusercontent.com/63288/114645751-e23efd00-9c8e-11eb-9397-ba85ff7552e2.png)

Select the **Build** tab.

|Field|Value
|-|-
| Name: | `Actions`
| Type: | Interactions Toolbar

Paste the following KATA into **Toolbar:**

```yaml
interaction/ticketMove:
  label: Move
  uri: cerb:automation:cerb.ticket.move
  icon: inbox-out
  hidden@bool: {{record__type is not record type ('ticket')}}
  inputs:
    ticket: {{record_id}}
  after:
    refresh_widgets@list:
      Actions
      Properties
```

Click the **Save Changes** button.

# How it works

Let's take a look at the interaction automation.

* Navigate to **Search -> Automations**.

* Search for: `cerb.ticket.move`

* Edit the automation record.

You'll see the following script:

```yaml
inputs:
  record/ticket:
    record_type: ticket
    required@bool: yes

start:
  await/group:
    form:
      title: Move ticket
      elements:
        sheet/prompt_group_id:
          label: To which group:
          required@bool: yes
          default: {{inputs.ticket.group_id}}
          data:
            automation:
              uri: cerb:automation:cerb.data.records
              inputs:
                record_type: group
                query_required: sort:name
          schema:
            layout:
              filtering@bool: yes
              headings@bool: no
              paging@bool: yes
            columns:
              selection/id:
                params:
                  mode: single
              card/_label:
                label: Group
                params:
                  bold@bool: yes
                  image@bool: yes
                  underline@bool: no
  
  set/group:
    group__context: group
    group_id: {{prompt_group_id|round}}
  
  await/bucket:
    form:
      elements:
        sheet/prompt_bucket_id:
          label: To which bucket in {{group__label}}:
          required@bool: yes
          data:
            automation:
              uri: cerb:automation:cerb.data.records
              inputs:
                record_type: bucket
                query_required@text,trim:
                  group.id:{{prompt_group_id|round}} sort:name
          default: {{group_default_bucket_id}}
          schema:
            layout:
              filtering@bool: yes
              headings@bool: no
              paging@bool: yes
            columns:
              selection/id:
                params:
                  mode: single
              card/_label:
                label: Bucket
                params:
                  bold@bool: yes
                  underline@bool: no

  set/bucket:
    bucket__context: bucket
    bucket_id: {{prompt_bucket_id|round}}
  
  record.update/ticket:
    output: updated_ticket
    inputs:
      # See: https://cerb.ai/docs/records/types/ticket/#records-api
      record_type: ticket
      record_id: {{inputs.ticket.id}}
      fields:
        group_id: {{bucket_group_id}}
        bucket_id: {{bucket_id}}
```

There's one required [input](https://cerb.ai/docs/automations/#inputs) for [record/ticket:](https://cerb.ai/docs/automations/inputs/record/). This accepts a ticket ID and loads the record into the `inputs.ticket` placeholder.

The interaction then prompts the current worker for a destination group in `await/group:`. The default is the ticket's current group. This [sheet:](https://cerb.ai/docs/automations/triggers/interaction.worker/elements/sheet/) prompt fetches group records using the `cerb.data.records` automation with a filter that sorts groups by name. It allows single record selection.

Once a group is selected, the [set/group:](https://cerb.ai/docs/automations/commands/set/) command loads that full record. The `{{prompt_group_id}}` placeholder from the sheet only gave us the selected ID. We'll use this to display the group's name and find its default bucket.

Next, the interaction prompts the worker for a destination bucket from the selected group in `await/bucket:`. The default is the group's default bucket (usually 'Inbox'). This [sheet:](https://cerb.ai/docs/automations/triggers/interaction.worker/elements/sheet/) prompt also fetches bucket records using the `cerb.data.records` automation with a filter for the selected group, and it sorts alphabetically. If you want to sort the buckets in a different order (e.g. an "order" custom field) you could do that here. This sheet allows single record selection.

Like earlier, once a bucket is selected the [set/bucket:](https://cerb.ai/docs/automations/commands/set/) command loads the full record. This is just a validation step before we update the ticket record so we're not directly trusting user input.

Finally, the [record.update:](https://cerb.ai/docs/automations/commands/record.update/) command updates the ticket's `group_id` and `bucket_id` fields with the selections.

At this point the interaction ends, and the `after:` actions run in the toolbar.

**Comment by LeeTV1** [comment]
This is excellent. How can we add a button if we want to change the owner?

**Reply by jstanden** [reply]
Hi @LeeTV1!

In Setup->Packages->Import, paste this:

```json
{
    "package": [],
    "records": [
        {
            "uid": "automation_64937be41cf80",
            "_context": "automation",
            "name": "example.ticket.assign",
            "extension_id": "cerb.trigger.interaction.worker",
            "description": "An interaction for quickly assigning tickets",
            "script": "inputs:\r\n  record/ticket:\r\n    record_type: ticket\r\n    required@bool: yes\r\n  text/unassign:\r\n    type: bool\r\n\r\nstart:\r\n  decision/action:\r\n    outcome/unassign:\r\n      if@bool: {{inputs.unassign}}\r\n      then:\r\n        set:\r\n          prompt_worker_id: 0\r\n    outcome/else:\r\n        then:\r\n          await/owner:\r\n            form:\r\n              title: Assign\r\n              elements:\r\n                sheet/prompt_worker_id:\r\n                  label: To which worker:\r\n                  required@bool: yes\r\n                  data:\r\n                    automation:\r\n                      uri: cerb:automation:cerb.data.records\r\n                      inputs:\r\n                        record_type: worker\r\n                        query: group:(id:{{inputs.ticket.group_id}}) isDisabled:n sort:firstName\r\n                  schema:\r\n                    layout:\r\n                      style: grid\r\n                      filtering@bool: yes\r\n                      headings@bool: no\r\n                      paging@bool: yes\r\n                    columns:\r\n                      selection/id:\r\n                        params:\r\n                          mode: single\r\n                      icon/image:\r\n                        params:\r\n                          record_uri@raw: cerb:worker:{{id}}\r\n                          text_size@raw: 250%\r\n                      text/_label:\r\n                        params:\r\n                          bold@bool: yes\r\n                          underline@bool: no\r\n                          text_size@raw: 125%\r\n                      text/title:\r\n                submit:\r\n                  continue@bool: no\r\n                  reset@bool: no\r\n\r\n  record.update/ticket:\r\n    output: updated_ticket\r\n    inputs:\r\n      # See: https://cerb.ai/docs/records/types/ticket/#records-api\r\n      record_type: ticket\r\n      record_id: {{inputs.ticket.id}}\r\n      fields:\r\n        owner_id: {{prompt_worker_id}}\r\n  ",
            "policy_kata": "commands:\r\n  record.update:\r\n    deny/type@bool: {{inputs.record_type is not record type ('ticket')}}\r\n    deny/fields@bool: {{inputs.fields|keys is not same as ['owner_id']}}\r\n    allow@bool: yes",
            "created_at": 1687387108,
            "updated_at": 1687387108
        }
    ]
}
```

That will create a new assignment interaction automation. It's identical to one added in the upcoming 10.4 update.

On a ticket card popup, click the toolbar gear at the top:

![CleanShot 2023-06-21 at 15 42 38@2x](https://github.com/cerb/cerb-release/assets/63288/05069979-122a-44f3-9dfe-4ca8aa85edad)

Add this toolbar item using the new interaction:

```yaml
interaction/assign:
  label: Assign
  uri: cerb:automation:example.ticket.assign
  icon: user
  inputs:
    ticket@key: record_id
  after:
    refresh_widgets@list: Properties
```

That adds an 'Assign' button to every ticket card popup that lets you quickly choose a worker.

The interaction is smart enough to only suggest workers who are in the ticket's group; but you can customize that logic by editing the automation.
