### DISCUSSION TITLE
10.0: Replace snippets with a fully customizable draft generator using interactions

### DISCUSSION THREAD

**Discussion by jstanden** [cerb/cerb-release#16] [Guides and Tutorials]
# Introduction

Let's assume your team composes and replies to clients daily using a couple different [snippet](https://cerb.ai/docs/snippets/) templates. That works great if all you need to do is paste some text into the current message.

However, you may find yourself also wanting to associate other presets with each template, like: group/bucket, status, waiting until time, custom fields, formatting, attachments, and so on.

With Cerb 10, you can use [interactions](https://cerb.ai/docs/interactions/) to generate a [draft](https://cerb.ai/docs/records/types/draft/) and instantly resume it. That gives you full control over every aspect of the draft.

In this guide we'll create an interaction shortcut on a workspace that generates a draft with presets.

# Import the example package

Navigate to **Setup -> Packages -> Import**.

Paste the following package:

```json
{
  "package": {
    "name": "Draft generator automation example",
    "requires": {
      "cerb_version": "10.0.0"
    }
  },
  "records": [
    {
      "uid": "automation_draft_gen",
      "_context": "automation",
      "name": "wgm.example.draft.generator",
      "description": "An example of generating a draft with presets",
      "extension_id": "cerb.trigger.interaction.worker",
      "script": "start:\n  await/type:\n    form:\n      title: Compose\n      elements:\n        sheet/prompt_type:\n          label: What type of message would you like to send?\n          required@bool: yes\n          default: exampleWelcome\n          data:\n            0:\n              key: exampleWelcome\n              name: Example welcome letter \n              description: Send a welcome letter to a new trial user.\n            1:\n              key: exampleFollowup\n              name: Example call follow-up\n              description: After a sales call, send a summary with next steps.\n          schema:\n            layout:\n              headings@bool: no\n              filtering@bool: no\n              paging@bool: no\n              title_column: name\n            columns:\n              selection/key:\n                params:\n                  mode: single\n              text/name:\n              text/description:\n  \n  decision:\n    outcome/exampleWelcome:\n      if@bool: {{prompt_type == 'exampleWelcome'}}\n      then:\n        record.create:\n          output: draft_record\n          inputs:\n            record_type: draft\n            fields:\n              type: mail.compose\n              worker_id: {{worker_id}}\n              params:\n                subject: Welcome to the product!\n                owner_id: {{worker_id}}\n                status_id: 1\n                ticket_reopen: tomorrow 8am\n                content@text:\n                  Welcome to the product!\n                  \n                  Have you seen these time-saving tips?\n                  https://product.example/link/\n                  \n                  #signature\n                  \n    outcome/exampleFollowup:\n      if@bool: {{prompt_type == 'exampleFollowup'}}\n      then:\n        record.create:\n          output: draft_record\n          inputs:\n            record_type: draft\n            fields:\n              type: mail.compose\n              worker_id: {{worker_id}}\n              params:\n                subject: Follow-up to our call\n                format: markdown\n                owner_id: {{worker_id}}\n                status_id: 1\n                ticket_reopen: 1 week 8am\n                content@text:\n                  Thanks for the great call!\n                  \n                  To summarize, we discussed:\n                  \n                  * \n                  \n                  #signature\n                  \n  # See: https://cerb.ai/docs/automations/triggers/interaction.worker/#awaitdraft\n  await/draft:\n    draft:\n      output: draft_result\n      uri: cerb:draft:{{draft_record.id}}\n\n  # If sent or saved, show the record link\n  outcome/sent:\n    if@bool: {{draft_result.status in ['compose.sent','compose.draft']}}\n    then:\n      await:\n        form:\n          elements:\n            sheet:\n              label@text:\n                {{\n                  draft_result.status == 'compose.sent'\n                  ? 'Message sent:'\n                  : 'Draft saved:'\n                }}              \n              data:\n                0@json: {{draft_result.record|json_encode}}\n              schema:\n                layout:\n                  filtering@bool: no\n                  headings@bool: no\n                  paging@bool: no\n                  title_column: id\n                columns:\n                  card/id:",
      "policy_kata": "commands:\n  record.create:\n    deny/type@bool: {{inputs.record_type is not record type ('draft')}}\n    allow@bool: yes"
    }
  ]
}
```

Click the **Import** button.

  <img width="266" alt="image" src="https://user-images.githubusercontent.com/63288/115408137-7afcdd80-a1a5-11eb-88ff-b13d544238c9.png">

# Add the interaction to your workspace

If you have an existing dashboard you'd like to use, you can navigate there and skip the next step.

## Create a new workspace and dashboard

Navigate to **Search -> Workspace Pages -> (+)**.

Select **Empty Workspace** from the library.

  <img width="714" alt="image" src="https://user-images.githubusercontent.com/63288/115410152-3ffba980-a1a7-11eb-840a-1fd46103dc38.png">

Set the owner to yourself for a private workspace, or **Cerb** for a shared one (or a role/group).

Name the workspace `Compose`.

Click the **Create** button.

  <img width="694" alt="image" src="https://user-images.githubusercontent.com/63288/115409700-da0f2200-a1a6-11eb-91a5-3c1ae267fa75.png">

Filter the pages worklist with:

```yaml
sort:-updated
```

Click on the new **Compose** page to open it.

Click on the **Add** button to create a new tab.

Select **Dashboard** from the library.

  <img width="750" alt="image" src="https://user-images.githubusercontent.com/63288/115410050-2b1f1600-a1a7-11eb-9c33-cadce519669d.png">

Name the new tab `Templates`.

  <img width="726" alt="image" src="https://user-images.githubusercontent.com/63288/115410467-82bd8180-a1a7-11eb-8a82-10bfa0a9d82b.png">

Click the **Create** button.

## Import the widget

Click the **Add Widget** button.

  ![image](https://user-images.githubusercontent.com/63288/115410649-aa144e80-a1a7-11eb-8cec-8081302337bb.png)

Select the **Import** tab.

Paste the following widget:

```json
{
    "widget": {
        "uid": "workspace_widget_draft_generator",
        "_context": "cerberusweb.contexts.workspace.widget",
        "label": "Draft Generator",
        "extension_id": "core.workspace.widget.form_interaction",
        "pos": 1,
        "width_units": 4,
        "zone": "content",
        "params": {
            "interactions_kata": "interaction/compose:\r\n  label: Compose\r\n  uri: cerb:automation:wgm.example.draft.generator\r\n  icon: send\r\n  #hidden@bool: no\r\n  after:\r\n    refresh_widgets@list: Draft Generator"
        }
    }
}
```

Click the **Save Changes** button.

# Using the interaction

Click the **Compose** button to start the interaction.

  ![image](https://user-images.githubusercontent.com/63288/115411029-fcee0600-a1a7-11eb-9bb8-874ec734c194.png)

Select the type of message to send:

  <img width="399" alt="image" src="https://user-images.githubusercontent.com/63288/115444595-9da0ed80-a1c9-11eb-960d-32da64f0448c.png">

The compose editor will open with several presets:

* Subject
* Owner
* Status
* Reopen at
* Content

This could also include any other [draft field](https://cerb.ai/docs/records/types/draft/#params-mailcompose).

  <img width="936" alt="image" src="https://user-images.githubusercontent.com/63288/115444687-bf01d980-a1c9-11eb-8aef-6c63523d6e4c.png">

From there you can finish the draft and send it.

As an interaction, you can also prompt for worker input before the draft is created and after the message is sent. You can provide inputs based on the current record being viewed.

For instance, if the compose button is on a card or profile (email, contact, org) you can also default the 'To:' and 'Org:' fields, and start the message with "Hello `{{first_name}}`".

# How it works

Navigate to **Search -> Automations**.

Edit the **wgm.example.draft.generator** automation.

```yaml
start:
  await/type:
    form:
      title: Compose
      elements:
        sheet/prompt_type:
          label: What type of message would you like to send?
          required@bool: yes
          default: exampleWelcome
          data:
            0:
              key: exampleWelcome
              name: Example welcome letter 
              description: Send a welcome letter to a new trial user.
            1:
              key: exampleFollowup
              name: Example call follow-up
              description: After a sales call, send a summary with next steps.
          schema:
            layout:
              headings@bool: no
              filtering@bool: no
              paging@bool: no
              title_column: name
            columns:
              selection/key:
                params:
                  mode: single
              text/name:
              text/description:
  
  decision:
    outcome/exampleWelcome:
      if@bool: {{prompt_type == 'exampleWelcome'}}
      then:
        record.create:
          output: draft_record
          inputs:
            record_type: draft
            fields:
              type: mail.compose
              worker_id: {{worker_id}}
              params:
                subject: Welcome to the product!
                owner_id: {{worker_id}}
                status_id: 1
                ticket_reopen: tomorrow 8am
                content@text:
                  Welcome to the product!
                  
                  Have you seen these time-saving tips?
                  https://product.example/link/
                  
                  #signature
                  
    outcome/exampleFollowup:
      if@bool: {{prompt_type == 'exampleFollowup'}}
      then:
        record.create:
          output: draft_record
          inputs:
            record_type: draft
            fields:
              type: mail.compose
              worker_id: {{worker_id}}
              params:
                subject: Follow-up to our call
                format: markdown
                owner_id: {{worker_id}}
                status_id: 1
                ticket_reopen: 1 week 8am
                content@text:
                  Thanks for the great call!
                  
                  To summarize, we discussed:
                  
                  * 
                  
                  #signature
                  
  # See: https://cerb.ai/docs/automations/triggers/interaction.worker/#awaitdraft
  await/draft:
    draft:
      output: draft_result
      uri: cerb:draft:{{draft_record.id}}

  # If sent or saved, show the record link
  outcome/sent:
    if@bool: {{draft_result.status in ['compose.sent','compose.draft']}}
    then:
      await:
        form:
          elements:
            sheet:
              label@text:
                {{
                  draft_result.status == 'compose.sent'
                  ? 'Message sent:'
                  : 'Draft saved:'
                }}              
              data:
                0@json: {{draft_result.record|json_encode}}
              schema:
                layout:
                  filtering@bool: no
                  headings@bool: no
                  paging@bool: no
                  title_column: id
                columns:
                  card/id:
```

First, the [interaction](https://cerb.ai/docs/automations/triggers/interaction.worker/) prompts the worker to choose a message type ("welcome letter" or "call follow-up") in `await/type`. These are just examples that you can modify to meet your needs.

The choices are displayed as a [sheet](https://cerb.ai/docs/automations/triggers/interaction.worker/elements/sheet/) and the worker's selection is saved as the `prompt_type` placeholder.

After the worker makes a selection, the `decision` runs different logic depending on their choice. The `outcome/exampleWelcome` and `outcome/exampleFollowup` [outcomes](https://cerb.ai/docs/automations/commands/outcome/) use [record.create](https://cerb.ai/docs/automations/commands/record.create/) to create a [draft record](https://cerb.ai/docs/records/types/draft/#params-mailcompose).

The draft is then resumed by the `await/draft:` state, which opens the compose editor and starts a [continuation](https://cerb.ai/docs/automations/#continuations) to wait for the response.

Finally, if the draft was sent (`compose.sent`) or saved (`compose.draft`), the corresponding [message](https://cerb.ai/docs/records/types/message/) or [draft](https://cerb.ai/docs/records/types/draft/) record is displayed in another sheet with a link to its card.

# Customizing the interaction

Add new message types (presets) to the `data:` property in `sheet/prompt_type:` near the top of the automation.

For each message type, add an `outcome/:` to the following `decision:`. Like the current examples, this should compare the `prompt_type` to the `key` of your message type. From there you can customize the default fields for a new draft of that type.

That should be it!

You can use the same approach for reply presets on ticket record profiles.
