### DISCUSSION TITLE
Replicate the previous Time Tracking functionality with automations

### DISCUSSION THREAD

**Discussion by cybertechcafe** [cerb/cerb-release#19] [Q&A] [answered]
My team used the Time Tracking functionality extensively in Cerb < 9.x for tracking productivity and (more importantly) billing.  We're working to replicate the functionality with automations in Cerb 10 and thought others may be trying to do the same.  For the record, I'm not a developer and this is my first stab at creating an automation, so it's admittedly messy code.  I've attached what we have so far with a quick summary below:

**What is working:**
- Create a new timetracking_entry
- Link the newly created timetracking_entry to the current ticket (where it was called from)

**What is not working:**
- Adding a comment to the timetracking_entry
- Also posting the comment to the ticket (this showed us where in the timeline 
- It's lacking any real feedback or error control

**Toolbar KATA:**
```
menu/menu_srqdg8:
  label: Ticket Actions
  icon: chevron-down
  hidden@bool: {{record__type is not record type ('ticket')}}
  #hidden@bool: no
  #badge: 0
  items:

    interaction/timetracking:
       label:  Time Tracking
       icon: clock 
       uri: ctc.automation.timetracking
       hidden@bool: {{record__type is not record type ('ticket')}}
       inputs:
         ticket: {{record_id}}
```

**Automation:**
```
inputs:
  record/ticket:
    record_type: ticket
    required@bool: yes
    
start:
  await: 
    form:
      title: Time Entry Form for {{inputs.ticket.mask}} for {{worker_first_name}}
      elements:
        text/prompt_work_done:
          label: Work Done
          default: 
        text/prompt_minutes_worked:
          label: Time Worked (in minutes)
          default: 
        text/prompt_date_logged:
          label: Date Logged
          default: {{'now'|date('F d, Y h:ia T')}}
        
        # Start the Activity box
        sheet/prompt_activity:
          label: Work Type:
          required@bool: yes
          data:
            automation:
              uri: cerb:automation:cerb.data.records
              inputs:
                record_type: timetracking_activity
                query_required@text:
                  isDisabled:n
          limit: 10
          schema:
            layout:
              headings@bool: no
              paging@bool: no
              filtering@bool: yes
            columns:
              selection/id:
                params:
                  mode: single
              text/_label:
                params:
                  bold@bool: yes
                  image@bool: yes
        # End the Activity box
  decision:
    outcome/have_data:
      if@bool: {{prompt_minutes_worked}}
      then:
        # await/confirmation:
          # form:
            # title: Confirm your entry
            # elements:
              # say/hello:
                # content@text: About to add time tracking activity - {{prompt_activity}}
        record.create/timetracking:
          output: new_timetracking
          inputs:
            # See: https://cerb.ai/docs/records/types/task/#records-api
            record_type: time_entry
            fields:
              worker_id: {{worker_id}}
              mins: {{prompt_minutes_worked}}
              log_date@date: {{prompt_date_logged}}
              activity_id: {{prompt_activity}}
              #is_closed: 0:
          on_error:
            await/fail:
              form:
                title: Failed to link time entry!
                elements:
                  say/hello:
                    content: There was an error {{on_error.error}} 
            return:
        decision:
          outcome/ready_to_link:
            if@bool: {{new_timetracking.id}}
            then:
              # await/success:
                # form:
                  # title: Ready to link the ticket!
                  # elements:
                    # say/hello:
                      # content: Created new time entry {{new_timetracking.id}}
              # Link the new timetracking_entry to the ticket
              record.update:
                output: linked_time_entry
                inputs:
                  record_type: time_entry
                  record_id: {{new_timetracking.id}}
                  fields:
                    links@list:
                      ticket: {{inputs.ticket.id}}
              # Create a comment on the time tracking entry
              record.create/comment:
                output: new_comment
                inputs:
                  record_type: comment
                  #comment: test comment
                  #time_entry: {{linked_time_entry.id}}
                  fields:
                    # author_context: worker
                    author_id: {{worker_id}}
                    comment: bob
                    context: {{_context}}
                    # target_context: time_entry
                    target_id: {{linked_time_entry}}
                on_error:
                  await/fail:
                    form:
                      title: Failed to add comment!
                      elements:
                        say/hello:
                          content: There was an error adding  {{new_comment.error}} 
                  return:
          outcome/not_ready_to_link:
            then:
              await/success:
                form:
                  title: Nothing to link
                  elements:
                    say/hello:
                      content: Nothing to link
              return:
    outcome/no_have_data:
      then:
       return:
```

**Comment by cybertechcafe** [comment]
Currently, when I try to add an entry, I get an error that context is not an editable field.  If I leave it blank or leave it out, I get an error that context is required.  Looking at the description of comments ([here](https://cerb.ai/docs/records/types/comment/)), it looks like there's an author_context and target_context but I'm not sure which it's talking about.  I'm using record.create (details [here](https://cerb.ai/docs/records/types/comment/)) to try to create the record.

- https://cerb.ai/docs/automations/commands/record.update/
- https://cerb.ai/docs/records/types/comment/

**Comment by jstanden** [comment, marked as answer]
Use:

```yaml
              # Create a comment on the time tracking entry
              record.create/comment:
                output: new_comment
                inputs:
                  record_type: comment
                  fields:
                    author__context: worker
                    author_id: {{worker_id}}
                    comment: test comment
                    target__context: time_entry
                    target_id: {{linked_time_entry.id}}
```

Main differences:

* `author__context` (two underscores, uncommented)
* `target__context` (two underscores, uncommented)
* `{{linked_time_entry.id}}` for the `target_id`
* Removed `context` (it's `target__context`)

**Reply by cybertechcafe** [reply]
That is awesome!  That changed it so that it will create a comment on the time tracking entry but it's not included in the ticket timeline.  I was able to change it (automation below) to create a comment on the ticket instead (a workaround, but it meets our needs) and have one other question.  Currently, we're just creating a one-line comment.  When I try to add multiple lines (I'd like for the Qty and Work Done to be on a separate line), I get an error that Qty isn't valid.  I've tried a couple of things (appended the @text annotation to the comment: key, indentation, quotes, curley brackets) but my barely educated guesswork didn't yield fruit.  I also tried cramming some <br /> tags in, but that didn't work either.   Ideally, I'd like the comment to look like this:

Time Tracking Entry
- Qty - {{prompt_minutes_worked}}
- Work Done - {{prompt_work_done}}



```
inputs:
  record/ticket:
    record_type: ticket
    required@bool: yes
    
start:
  await: 
    form:
      title: Time Entry Form for {{inputs.ticket.mask}} for {{worker_first_name}}
      elements:
        text/prompt_work_done:
          label: Work Done
          default: 
        text/prompt_minutes_worked:
          label: Time Worked (in minutes)
          default: 
        text/prompt_date_logged:
          label: Date Logged
          default: {{'now'|date('F d, Y h:ia T')}}
        
        # Start the Activity box
        sheet/prompt_activity:
          label: Work Type:
          required@bool: yes
          data:
            automation:
              uri: cerb:automation:cerb.data.records
              inputs:
                record_type: timetracking_activity
                query_required@text:
                  isDisabled:n
          limit: 10
          schema:
            layout:
              headings@bool: no
              paging@bool: no
              filtering@bool: yes
            columns:
              selection/id:
                params:
                  mode: single
              text/_label:
                params:
                  bold@bool: yes
                  image@bool: yes
        # End the Activity box
  decision:
    outcome/have_data:
      if@bool: {{prompt_minutes_worked}}
      then:
        # await/confirmation:
          # form:
            # title: Confirm your entry
            # elements:
              # say/hello:
                # content@text: About to add time tracking activity - {{prompt_activity}}
        record.create/timetracking:
          output: new_timetracking
          inputs:
            # See: https://cerb.ai/docs/records/types/task/#records-api
            record_type: time_entry
            fields:
              worker_id: {{worker_id}}
              mins: {{prompt_minutes_worked}}
              log_date@date: {{prompt_date_logged}}
              activity_id: {{prompt_activity}}
              #is_closed: 0:
          on_error:
            await/fail:
              form:
                title: Failed to link time entry!
                elements:
                  say/hello:
                    content: There was an error {{on_error.error}} 
            return:
        decision:
          outcome/ready_to_link:
            if@bool: {{new_timetracking.id}}
            then:
              # await/success:
                # form:
                  # title: Ready to link the ticket!
                  # elements:
                    # say/hello:
                      # content: Created new time entry {{new_timetracking.id}}
              # Link the new timetracking_entry to the ticket
              record.update:
                output: linked_time_entry
                inputs:
                  record_type: time_entry
                  record_id: {{new_timetracking.id}}
                  fields:
                    links@list:
                      ticket: {{inputs.ticket.id}}
              # Create a comment on the time tracking entry
              record.create/comment:
                output: new_comment
                inputs:
                  record_type: comment
                  fields:
                    author__context: worker
                    author_id: {{worker_id}}
                    comment: Time Tracking Added Qty - {{prompt_minutes_worked}} Work Done - {{prompt_work_done}}}
                    target__context: ticket
                    target_id: {{inputs.ticket.id}}
                on_error:
                  await/fail:
                    form:
                      title: Failed to add comment!
                      elements:
                        say/hello:
                          content: There was an error adding  {{new_comment.error}} 
                  #return:
          outcome/not_ready_to_link:
            then:
              await/success:
                form:
                  title: Nothing to link
                  elements:
                    say/hello:
                      content: Nothing to link
              return:
    outcome/no_have_data:
      then:
       return:
```

**Reply by jstanden** [reply]
For a multi-line value using the `@text` annotation, you need to make sure the entire value is indented one level below the parent.

See `comment@text:` on:

```yaml
              # Create a comment on the time tracking entry
              record.create/comment:
                output: new_comment
                inputs:
                  record_type: comment
                  fields:
                    author__context: worker
                    author_id: {{worker_id}}
                    is_markdown: 1
                    comment@text:
                      Time Tracking Added
                      * Qty - {{prompt_minutes_worked}}
                      * Work Done - {{prompt_work_done}}}
                    target__context: ticket
                    target_id: {{inputs.ticket.id}}
```

I added `is_markdown: 1` there too so your asterisks make a bullet-point list as expected.
