### DISCUSSION TITLE
10.0: Queue, schedule, and deliver outgoing mail from automations

### DISCUSSION THREAD

**Discussion by jstanden** [cerb/cerb-release#23] [Guides and Tutorials]
# Introduction

[Automations](https://cerb.ai/docs/automations/) can send or schedule "transactional" (automated, event-based) email using the mail queue.

This is accomplished by creating a queued draft. The delivery of these messages can be monitored from a drafts worklist of **Setup -> Mail -> Outgoing -> Queue**. Temporarily failed deliveries will be automatically retried.

# Creating a sample automation for creating drafts

Log into Cerb as an administrator.

Navigate to **Search -> Automations -> (+)**.

Set the **Trigger:** to **automation.function**.

Paste the following example automation:

```yaml
start:
  record.create:
    output: new_draft
    inputs:
      record_type: draft
      # See: https://cerb.ai/docs/records/types/draft/
      fields:
        type: mail.transactional
        to: customer@cerb.example
        name: New draft
        is_queued: 1
        queue_delivery_date@date: now
        params:
          to: customer@cerb.example
          subject: This is a queued message from a Cerb automation
          format: parsedown
          content@text:
            This is the **formatted** content of the queued message.
            
            -- 
            Example signature
            [cerb.ai](https://cerb.ai/)
```

You can replace `customer@cerb.example` above with your personal email address for testing.

Select the **Policy** tab and paste the following policy:

```yaml
commands:
  record.create:
    deny/type@bool: {{inputs.record_type is not record type ('draft')}}
    allow@bool: yes
```

Select the **Run** tab and click on the play icon.

![image](https://user-images.githubusercontent.com/63288/116489152-1b5b9d80-a849-11eb-9961-9cc07fddfd69.png)

You should see output like:

```yaml
__exit: exit
new_draft:
  _context: cerberusweb.contexts.mail.draft
  id: "123"
  _type: draft
  _loaded: true
  _label: New draft
  name: New draft
  to: customer@cerb.example
  token: iDqY8YKwHv
  updated: "1619656737"
  worker_id: "0"
  subject: New draft
```

If you navigate to **Search->Drafts**, you'll see a new outgoing message in the queue.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/63288/116489295-8311e880-a849-11eb-971b-556fa4e12b27.png">

<img width="710" alt="image" src="https://user-images.githubusercontent.com/63288/116489309-89a06000-a849-11eb-81f6-4aa9811abe7a.png">
