### DISCUSSION TITLE
Categorize work performed on tickets

### DISCUSSION THREAD

**Discussion by cybertechcafe** [cerb/cerb-release#25] [Q&A]
We are a small MSP and would like to better understand our customers needs based on what they're asking us to do for them.  Our plan is to 'categorize' each ticket based on a set number of questions (noted below) and then report on that data by organization and aggregate once we have a sample of the tickets categorized.  The specific questions that we want to answer are:

- What was done?
- What was it done to?
- Was the work done planned or unplanned?

So far, we've created a Custom Record called "Ticket_Categorization".  That custom ticket has the following nine custom fields:
- Event Type (Planned | Unplanned)
- Event Category (Hardware | Software | Network | Security | Service | Administrative)
- Hardware (New | Upgrade | Failure)
- Software (Install | Remove | Reconfigure)
- Network (New | Upgrade | Failure)
- Security (BEC | Phishing | SMishing | Brute Force)
- Service (Microsoft 365 | Internet | Power)
- Administrative (Add User | Edit User | Remove User | Password Reset)
- Device (Phone / Tablet | Workstation | Server | Printer | Switch | Firewall)

I'd like to create an interaction from a toolbar that presents the user with a form that guides them through those questions, creates the Ticket_Categorization record and then links it to the ticket.
- What was the Event Type?  Drop down with options populated form the Event Type field.
- What was the Event Category?  Drop down with options populated from the Event Category field.  Note that the options in the Event Category would correspond to the next several fields (between Event Category and Device)
- What was done.  This would be another drop down populated by one of the fields with a name corresponding to the Event Category chosen  For example, if the user chose Event Category: Hardware, the options from the Hardware field would be shown.  
- What device.  Drop down with the options populated from the Device field.
- An optional comment field.
- Once the fields were completed, this would create a new Ticket_Categorization record that was linked to the current ticket.

I'm still very much in the beginning phase of this and don't have any code that I'm not embarrassed to share but thought someone else may be trying to do the same thing and a) may be further along and wanted to share what they have or b) isn't as far along and may benefit from what I have so far.

**Comment by cybertechcafe** [comment]
Below is my first stab at the automation for this.  Very raw at this point but hoping that it better illustrates what we're trying to do:

```
inputs:
  record/ticket:
    record_type: ticket
    required@bool: yes
    
start:
  await: 
    form:
      title: Ticket Categorization
      elements:
        # This should come from the tc.event_type options.  Can data.query be used here?
        text/prompt_event_type:
          label: Event Type
          default: 
        # This should come from the tc.event_category options.  Can data.query be used here?
        text/prompt_event_category:
          label: Event Category
          default:
        # This should come from the tc.event_category options.  Can data.query be used here?
        # This will be a custom field with the same  name as the 
        # Event Category chosen above.
        text/prompt_sub_category:
          label: Sub Category
          default:
        # This should come from the tc.device options.  Can data.query be used here?
        text/prompt_event_device:
          label: Device
          default:
        # If populated, this will be a comment on the Ticket Categorization record
        textarea/prompt_comments:
          label: Additional Details
          default: 
  record.create/ticket_categorization:
    output: new_ticket_categorization
    inputs:
      fields:
        Event Type: {{prompt_event_type}}
        Event Category: {{prompt_event_category}}
        Hardware: {{prompt_event_hardware}}
        Software: {{prompt_event_software}}
        Network: {{prompt_event_network}}
        Security: {{prompt_event_security}}
        Service: {{prompt_event_service}}
        Administrative: {{prompt_event_administrative}}
        Device: {{prompt_event_device}}
    on_error:
      await/fail:
        form:
          title: Failed to create the Ticket Categorization!
          elements:
            say/hello:
              content: There was an error {{on_error.error}}
  decision:
    outcome/ready_to_link:
      if@bool: {{new_ticket_categorization.id}}
        then:
          # Link the Ticket Categorization to the Ticket
          
          on_success:
            # If there's a comment, link it to the Ticket Categorization
           {% if prompt_event_comment %}
            record.create/comment:
              output: new_comment
              inputs:
                record_type: comment
                fields:
                  author__context: worker
                  author_id: {{worker_id}}
                  comment@text: 
                    {{prompt_event_comment}}
                  target__context: Ticket Categorization
                  target_id: {{new_ticket_categorization.id}}
           {% endif %}
             
    outcome/fail:
      then:
        return:
    
```
