### DISCUSSION TITLE
10.0: Create new records from an interaction

### DISCUSSION THREAD

**Discussion by jstanden** [cerb/cerb-release#26] [Guides and Tutorials]
# Introduction

A common use case for [interactions](https://cerb.ai/docs/interactions/) is creating new records.

This guide demonstrates the two most common ways to create records from interaction [automations](https://cerb.ai/docs/automations/).

# Use the await:record: continuation

You can open the built-in record editor popup from an interaction with the [await:record:](https://cerb.ai/docs/automations/triggers/interaction.worker/#awaitrecord) continuation.

Once the record is saved, the continuation returns an `event` and the saved `record` dictionary.

In the following `interaction.worker` interaction, the task editor opens to create a new record. After saving, the newly created record is automatically linked to a project board column.

```yaml
inputs:
  record/column:
    record_type: project_board_column
    required@bool: yes

start:
  await:
    record:
      uri: cerb:task
      output: result
  outcome:
    if@bool: {{result.record._context and result.record.id}}
    then:
      record.update:
        output: new_record
        inputs:
          record_type: {{result.record._context}}
          record_id: {{result.record.id}}
          fields:
            links@list:
              project_board_column:{{inputs.column.id}}
```

  <img width="744" alt="image" src="https://user-images.githubusercontent.com/63288/116756894-d0b16100-a9c1-11eb-9205-4dd575e89427.png">

# Create your own editor with interactions

This above continuation works well for most use cases. However, it does require that workers have access to create records of the desired type.

You can also use an interaction to display a form and create a record type that workers couldn't create for themselves. This is particularly common with custom records.

This `interaction.worker` interaction displays a form for gathering fields, then it creates a new task.

```yaml
start:
  await:
    form:
      title: New task
      elements:
        text/prompt_title:
          label: Name:
          required@bool: yes
          
        text/prompt_due:
          label: Due:
          type: date
          
        sheet/prompt_status:
          label: Status:
          required@bool: yes
          data:
            0:
              key: open
              label: Open
              description: The task is not complete
            1:
              key: waiting
              label: Waiting
              description: The task is waiting for other parties or dependencies
            2:
              key: closed
              label: Closed
              description: The task is complete
          default: open
          schema:
            layout:
              headings@bool: no
            columns:
              selection/key:
                params:
                  mode: single
              text/label:
                params:
                  bold@bool: yes
              text/description:
              
        sheet/prompt_owner:
          label: Owner:
          required@bool: yes
          data:
            automation:
              uri: cerb:automation:cerb.data.records
              inputs:
                record_type: worker
                query_required: isDisabled:n
          schema:
            layout:
              headings@bool: no
            columns:
              selection/id:
                params:
                  mode: single
              card/_label:
                params:
                  image@bool: yes
                  bold@bool: yes
                  underline@bool: no
              text/title:
  
  record.create:
    output: new_task
    inputs:
      record_type: task
      fields:
        title: {{prompt_title}}
        status: {{prompt_status}}
        due@date: {{prompt_due}}
        owner_id: {{prompt_owner|round}}
```

  <img width="656" alt="image" src="https://user-images.githubusercontent.com/63288/116756852-b5465600-a9c1-11eb-8082-214dd0549e3a.png">

The above interaction demonstrates how to use a [sheet element](https://cerb.ai/docs/automations/triggers/interaction.worker/elements/sheet/) with both hardcoded and dynamic data.
