### DISCUSSION TITLE
10.0: Use sheets for multiple selection to set record links custom fields from interactions

### DISCUSSION THREAD

**Discussion by jstanden** [cerb/cerb-release#27] [Guides and Tutorials]
# Introduction

Let's assume you've followed the guide [Tags and multi-classification using custom records](https://github.com/cerb/cerb-release/discussions/22).

And now you want to create an interaction that prompts a worker for some tags and sets them on a ticket.

We'll continue to build on that example.

# Building the tagging interaction

## Display tags on ticket profiles

First, let's make sure the new 'Tags' custom field is visible on ticket profiles.

Navigate to any ticket profile from **Search -> Tickets**.

Click on the **Ticket** widget in the sidebar and select **Edit** from the menu.

On the **Fields** tab, select **Tags**, and click the **Save Changes** button.

  ![image](https://user-images.githubusercontent.com/63288/116759077-4c151180-a9c6-11eb-8305-86e4056f0c8e.png)

You'll now see the tags for every ticket:

  ![image](https://user-images.githubusercontent.com/63288/116759117-736bde80-a9c6-11eb-9c3b-e6ad21b2a785.png)

## Create the interaction

Navigate to **Search -> Automations -> (+)**.

|Field|Value
|-|-
|Name:|`wgm.example.interaction.tagging`
|Description:|`An example multi-selection interaction for tagging`
|Trigger:|**interaction.worker**

In the editor, paste:

```yaml
inputs:
  record/ticket:
    record_type: ticket
    required@bool: yes

start:
  await:
    form:
      title: Tag ticket
      elements:
        sheet/prompt_tag_ids:
          label: Select tags: 
          data:
            automation:
              uri: cerb:automation:cerb.data.records
              inputs:
                record_type: tag
          default@csv: {{inputs.ticket.tags|join(',')}}
          schema:
            layout:
              filtering@bool: yes
              headings@bool: no
              paging@bool: yes
            columns:
              selection/id:
                params:
                  mode: multiple
              card/_label:
                params:
                  bold@bool: yes
                  underline@bool: no
  
  record.update:
    output: updated_ticket
    inputs:
      record_type: ticket
      record_id: {{inputs.ticket.id}}
      fields:
        tags@csv: {{prompt_tag_ids|join(',')}}
```

On the **Policy** tab, paste:

```yaml
commands:
  record.update:
    deny/type@bool: {{inputs.record_type is not record type ('ticket')}}
    deny/fields@bool: {{inputs.fields|keys|sort != ['tags']}}
    allow@bool: yes
```

Click the **Save Changes** button.

## Add the interaction to the ticket profile toolbar

Now let's add the new interaction to the toolbar at the top of ticket profiles.

Click on the gear to the right of the ticket profile toolbar.

  ![image](https://user-images.githubusercontent.com/63288/116761387-5e924980-a9cc-11eb-9d8b-ad70288ce7b9.png)

Paste the following Toolbar KATA:

```yaml
interaction/tags:
  tooltip: Tags
  uri: cerb:automation:wgm.example.interaction.tagging
  icon: tags
  inputs:
    ticket: {{record_id}}
  hidden@bool: {{record__type is not record type ('ticket')}}
  after:
    refresh_widgets@list:
      Ticket
```

Click the **Save Changes** button.

You should see a new button in the toolbar.

  <img width="658" alt="image" src="https://user-images.githubusercontent.com/63288/116761541-cea0cf80-a9cc-11eb-947d-413f46ad6fb8.png">

When you click the button, you can change the tags on the ticket and the results are saved to the custom field as links to records in the custom 'Tags' type.

https://user-images.githubusercontent.com/63288/116762211-8a163380-a9ce-11eb-9ff2-cbd23fbded76.mov
