### DISCUSSION TITLE
10.1: Send an automatic confirmation on new tickets using automations

### DISCUSSION THREAD

**Discussion by jstanden** [cerb/cerb-release#40] [Guides and Tutorials]
# Introduction

The Cerb [10.1](https://cerb.ai/releases/10.1/) update introduces a [mail.received](https://cerb.ai/docs/automations/events/mail.received/) event to simplify automations that react to new inbound messages.

In this guide, we'll use the event to create an automatic reply for confirming new tickets.

# Creating an auto-reply automation

Navigate to **Search >> Automation Events**.

Edit the **mail.received** event.

Click the 'magic wand' icon above the editor:

<kbd>![image](https://user-images.githubusercontent.com/63288/128428599-850e670e-61a3-4cfa-ad1d-67f3af56451a.png)</kbd>

Select **Auto-reply** from the **Generate an automation** list.

<kbd><img width="716" alt="image" src="https://user-images.githubusercontent.com/63288/128428719-36e966c3-c859-4014-8923-ec2728b3d4ec.png"></kbd>

Click the blue **Continue** button.

The prefix of the automation name is randomly generated. You can replace it with something unique to your organization:

<kbd><img width="715" alt="image" src="https://user-images.githubusercontent.com/63288/128428885-8559a1cd-83d1-4a40-b67b-b6a2a940a7d5.png"></kbd>

Click the blue **Continue** button.

The new auto-reply automation is automatically configured for you on the **mail.received** event for inbound messages that open a new ticket.

<kbd><img width="659" alt="image" src="https://user-images.githubusercontent.com/63288/128428964-12378141-af53-4eeb-a39c-fafe2ba6e5a6.png"></kbd>

Before saving the event you can customize the auto-reply email.

Hold <kbd>CMD</kbd> (Mac) or <kbd>CTRL</kbd> (Windows/Linux) and click on the `cerb:automation:example.mail.received.autoReply` text in the editor. Then click **Edit** at the top of the card popup.

This is the auto-reply automation by default:

```yaml
start:
  # Don't send auto-replies to automated senders
  outcome/isAutoSender:
    if@bool:
      {{
        message_sender_email is prefixed ('postmaster@','mailer-daemon@')
        or message_headers['auto-submitted'] is prefixed ('auto-')
        or message_headers['precedence'] == 'bulk'
        or message_headers['preference'] == 'auto_reply'
        or message_headers['x-precedence']
        or message_headers['x-autorespond']
        or message_headers['x-autogenerated']
        or message_headers['x-autoreply-from']
        or 'all' == message_headers['x-auto-response-suppress']|lower
        or 'autoreply' in message_headers['x-auto-response-suppress']|lower
        or 'out of office' in message_headers['subject']|lower
        or 'out of the office' in message_headers['subject']|lower
      }}    
    then:
      return:
  
  # See: https://cerb.ai/docs/automations/commands/record.create/
  record.create/draft:
    output: new_draft
    inputs:
      record_type: draft
      # See: https://cerb.ai/docs/records/types/draft/#records-api
      fields:
        type: mail.transactional
        name: Auto-reply to {{message_sender_email}}
        to: {{message_sender_email}}
        is_queued: 1
        queue_delivery_date@date: now
        params:
          to: {{message_sender_email}}
          from: support@cerb.example
          subject: Auto-Reply: {{message_ticket_subject}}
          headers:
            Auto-Submitted: auto-replied
            Precedence: bulk
          content@text:
            Thanks for writing!
            
            Your reference number is #{{message_ticket_mask}}.
```

In `outcome/isAutoSender` the automation first checks if the new message was sent by an automated sender (an auto-reply, newsletter, bounce, etc). If so, it uses `return:` to exit early without sending an email.

If the new message didn't self-identify as an automated sender, the automation creates a new `mail.transactional` draft record to send back to the message sender. Transactional messages are not stored in the ticket conversation. This draft is queued for immediate delivery.

You can edit `start:record.create/draft:inputs:fields:params:` to modify the `from:`, `subject:`, and `content:` of the auto-reply email.

You can test the automation by targeting a message in the **Inputs:** panel.

```yaml
message__context: message
message_id: 1
```

<kbd><img width="725" alt="image" src="https://user-images.githubusercontent.com/63288/128429622-0e6ba247-996f-44bc-88d6-871c515ebe2d.png"></kbd>

Prior to testing, you may want to temporarily disable the **Mail Queue** job in **Setup >> Configure >> Scheduler**. This will prevent your message from being sent until you review it. Remember to re-enable the job after you're done or no other queued mail will be sent.

You'll find the queued auto-reply draft in **Search >> Drafts**. You can either delete it or let it send.

Once you're satisfied with the changes, click the **Save Changes** button on the popups for both the automation and the event.

You can also test with a new inbound message from **Setup >> Mail >> Incoming >> Import** by pasting a message like the following:

```text
From: customer@cerb.example
To: support@cerb.example
Subject: This is a test subject.

This is a test message.
```

And clicking the **Import** button.

You should see a corresponding auto-reply in **Search >> Drafts**.

If you want to confirm that inbound replies to existing tickets don't create an auto-reply, you can import a message like:

```text
From: customer@cerb.example
To: support@cerb.example
Subject: [#ABC-12345-678] This is a reply.

This is a reply message.
```

Where `ABC-12345-678` above is an existing ticket mask in your system.

# Conclusion

You now know how to create an automatic reply in response to inbound messages. This event can be used for any action -- Slack notifications about new mail from important clients, etc.

**Comment by mryanb** [comment]
What is the best way to put the message content into a template so that other workers could adjust without going into the automation?

**Reply by jstanden** [reply]
We handled that with behaviors previously using role-owned snippets, along with the 'Set placeholder with snippet' action.

Automations could use something similar. You can load a snippet's content from an automation; but we probably need a simpler way to use an arbitrary dictionary for placeholder substitution.

If you want to make up your own placeholders, then you could use a custom record, a custom fieldset on the automation, etc. An interaction on the automation profile/card could update it.

Filed as: https://github.com/jstanden/cerb/issues/1511

**Reply by jstanden** [reply]
This is possible in recent versions with the `kata.parse:` command: https://cerb.ai/docs/automations/commands/kata.parse/

The 10.5 release has a workflow template that uses this approach:

```yaml
workflow:
  name: cerb.auto_responder
  version@date: 2024-10-07T00:00:00Z
  description: Send an automatic response when new tickets are opened
  requirements:
    cerb_version: >=10.5 <11.0
    cerb_plugins: cerberusweb.core,

records:
  snippet/snippet_autoresponder:
    updatePolicy@csv:
    fields:
      title: Ticket Auto-Response
      context: cerberusweb.contexts.ticket
      owner__context: app
      owner_id: 0
      content@raw:
        Thanks for contacting us! We'll get back to you as soon as possible.

        Reference #: {{mask}}
        Subject: {{subject}}

  automation/automation_autoresponder:
    fields:
      name: cerb.autoResponder.mailReceived
      extension_id: cerb.trigger.mail.received
      script@raw:
        start:
          set:
            snippet__context: snippet
            snippet_id: {{cerb_workflow_resources('cerb.auto_responder')['records']['snippet/snippet_autoresponder']}}

          kata.parse:
            output: results
            inputs:
              kata:
                template: {{snippet_content}}
              dict@json:
                {% do message_ticket_ %}
                {{cerb_placeholders_list('message_ticket_', '')|json_encode}}

          record.create:
            output: new_draft
            inputs:
              record_type: draft
              fields:
                name: Auto-Response
                type: ticket.reply
                ticket_id: {{message_ticket_id}}
                is_queued: 1
                queue_delivery_date@date: 5 mins
                to: {{message_sender_address}}
                params:
                  to: {{message_sender_address}}
                  subject: [#{{message_ticket_mask}}] {{message_ticket_subject}}
                  headers:
                    In-Reply-To@optional: {{message_headers['in-reply-to']}}
                    Auto-Submitted: auto-replied
                  content: {{results.template}}
      policy_kata@raw:
        commands:
          record.create:
            deny/type@bool: {{inputs.record_type is not record type ('draft')}}
            allow@bool: yes

  automation_event_listener/listener_mail_received:
    fields:
      name: Email Auto-Responder
      event_name: mail.received
      priority: 10
      is_disabled: 0
      event_kata@raw:
        automation/autoresponder:
          uri: cerb:automation:cerb.autoResponder.mailReceived
          # Exclude automated senders
          disabled@bool:
            {{
              not is_new_ticket
              or message_sender_is_banned
              or message_sender_is_defunct
              or message_sender_address is pattern (
                'mailer-daemon@*',
                'postmaster@*',
                'noreply@*',
                'no-reply@*',
              )
              or message_headers['auto-submitted']
              or message_headers['x-autogenerated']
              or message_headers['x-autoreply']
              or message_headers['x-autoreply-from']
              or message_headers['x-autorespond']
              or 'auto_reply' == message_headers['x-precedence']
              or 'auto_reply' == message_headers['preference']
              or 'bulk' == message_headers['precedence']
              or message_ticket_subject is pattern (
                '*out of the office*',
                '*out of office*',
                '*auto response*',
                '*autoreply*',
              )
            }}
```
