### DISCUSSION TITLE
[In Progress] 10.2: Integrate Cerb and Jira using OAuth2

### DISCUSSION THREAD

**Discussion by jstanden** [cerb/cerb-release#44] [Guides and Tutorials]
# Introduction

Using [automations](https://cerb.ai/docs/automations/) and [connected accounts](https://cerb.ai/docs/connected-accounts/) in Cerb, you can integrate with the full [Jira Cloud API](https://developer.atlassian.com/cloud/jira/platform/rest/v2/intro/).

# Configure OAuth in Jira

## Create an OAuth app

Log into the [Jira developer console](https://developer.atlassian.com/console/myapps/).

Click the blue **Create** button in the top right and select **OAuth 2.0 integration**.

Use the name **Cerb integration**, agree to the terms, and click the **Create** button.

## Add permissions

In your new Jira app, open the **Permissions** section and click the **Add** button for **Jira platform REST API**.

<kbd>![image](https://user-images.githubusercontent.com/63288/146694051-bcba8cb0-3655-4c11-8840-43f1cf232e81.png)</kbd>

Click the new **Configure** button for **Jira platform REST API**.

<kbd>![image](https://user-images.githubusercontent.com/63288/146694085-f90622dc-3665-45b7-af59-89300e637e3d.png)</kbd>

Add permissions for **View Jira issue data** and **Create and manage issues**.

## Configure authorization

In your new Jira app, click on **Authorization** in the left sidebar.
Click the **Configure** button for **OAuth 2.0 (3LO)**. 

<kbd>![image](https://user-images.githubusercontent.com/63288/146694160-dd921a86-a058-4188-81fe-2ae2bcdfa934.png)</kbd>

Use rotating refresh tokens.

Add a callback URL for `https://example.com/oauth/callback` where `example.com` is your Cerb host. In Cerb Cloud this will be something like `example.cerb.me`.

## Credentials

Click on **Settings** in the left sidebar.

Copy the **Client ID** and **Secret** to use in Cerb.

# Create a connected service and account in Cerb

Log into Cerb as an administrator.

## Create a connected service

First we need a connected service to define the integration between Cerb and Jira. We'll use the OAuth2 credentials from Jira that we created above.

Navigate to **Search > Connected Services**.

Click the **(+)** icon in the top right of the worklist.

Select the **Build** tab.

Field | Value
|---|---
|**Name:**| Jira
|**URI:**| `jira`
|**Type:**| OAuth2 provider
|**Grant Type:**| Authorization Code
|**Client ID:**| (paste from above)
|**Client Secret:**| (paste from above)
|**Authorization URL:**| `https://auth.atlassian.com/authorize?audience=api.atlassian.com`
|**Token URL:**| `https://auth.atlassian.com/oauth/token`
|**Resource URL:**| `https://api.atlassian.com/oauth/token/accessible-resources`
|**Scope:**| `offline_access read:jira-user write:jira-work read:jira-work`
|**Approval Prompt:**| `consent`

Click the **Save Changes** button to create the connected service.

<kbd><img width="728" alt="image" src="https://user-images.githubusercontent.com/63288/146825875-ac9afb1e-d987-4725-a1aa-2009b73bb4b3.png"></kbd>

## Create a connected account

With OAuth2, each Jira user can consent to link their own account to Cerb. However, it's common for a team to add a **Cerb** user to their Jira environment for automations.

In Cerb, OAuth-based connected services may have one or more connected **accounts**.

Navigate to **Search > Connected Accounts**.

Click the **(+)** icon in the top right of the worklist.

Select the **Jira** service.

Use the following details:

| Field | Value
|---|---
|**Name:**| `Jira (Cerb)`
|**URI:**| `jira-cerb`
|**Owner:**| Cerb

Click the blue **Link to Jira** button to link your account.

<kbd>![image](https://user-images.githubusercontent.com/63288/146694721-e1ff56e4-fee2-4868-9631-4967a58513e9.png)</kbd>

Accept the integration.

<kbd>![image](https://user-images.githubusercontent.com/63288/146826202-0cebd8aa-532a-4273-af7c-dbeec32ec5ca.png)</kbd>

# Examples

Navigate to **Search > Automations**.

Click the **(+)** icon in the top right of the worklist to add a new automation.

| Field | Value
|:--|:--
|**Trigger:**| `automation.function`

Paste the following into the **Policy** tab:

```yaml
commands:
  http.request:
    deny/url@bool: {{inputs.url is not prefixed ('https://api.atlassian.com/')}}
    allow@bool: yes
```

Let's fetch the **Cloud ID** for your preferred site.

Paste the following automation:

```yaml
start:
  http.request/fetchResources:
    output: http_response
    inputs:
      method: GET
      url: https://api.atlassian.com/oauth/token/accessible-resources
      authentication: cerb:connected_account:jira-cerb
    on_success:
      return:
        sites@json: {{http_response.body}}
```

In the **Run** tab, click the <img width="31" alt="image" src="https://user-images.githubusercontent.com/63288/146832082-941f68d2-92ac-4015-9a91-33bc57665073.png"> icon.

![image](https://user-images.githubusercontent.com/63288/146827975-486e52bc-291d-4546-9509-6f569e26ea37.png)

You can use the **Cloud ID** to access any of Jira's API endpoints.

## Search projects

```yaml
start:
  # See: https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-projects/#api-rest-api-2-project-search-get
  http.request/getProjects:
    output: http_response
    inputs:
      method: GET
      url: https://api.atlassian.com/ex/jira/a1b2c3-d4e5-f6a1-b2c3-d4e5f6a1b2c3/rest/api/2/project/search
      authentication: cerb:connected_account:jira-cerb
    on_success:
      return:
        projects@json: {{http_response.body}}
```

## Search issues

```yaml
start:
  # See: https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-search/#api-rest-api-2-search-post
  http.request/searchIssues:
    output: http_response
    inputs:
      method: POST
      url: https://api.atlassian.com/ex/jira/a1b2c3-d4e5-f6a1-b2c3-d4e5f6a1b2c3/rest/api/2/search
      authentication: cerb:connected_account:jira-cerb
      headers:
        Content-Type: application/json
      body:
        jql@text:
          project = "Cerb" AND key = "CERB-123"
    on_success:
      return:
        issues@json: {{http_response.body}}
```

## Get issue creation metadata

```yaml
start:
  # See: https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-createmeta-get
  http.request/createIssue:
    output: http_response
    inputs:
      method: GET
      url: https://api.atlassian.com/ex/jira/a1b2c3-d4e5-f6a1-b2c3-d4e5f6a1b2c3/rest/api/2/issue/createmeta?projectKeys=CERB,DEVBLOCKS
      authentication: cerb:connected_account:jira-cerb
      headers:
        Accept: application/json
    on_success:
      return:
        issues@json: {{http_response.body}}
```

## Create an issue

```yaml
start:
  # See: https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-post
  http.request/createIssue:
    output: http_response
    inputs:
      method: POST
      url: https://api.atlassian.com/ex/jira/a1b2c3-d4e5-f6a1-b2c3-d4e5f6a1b2c3/rest/api/2/issue
      authentication: cerb:connected_account:jira-cerb
      headers:
        Accept: application/json
        Content-Type: application/json
      body:
        fields:
          summary: Testing issue creation from Cerb
          description@text:
            This is a description.
          project:
            key: CERB
          issuetype:
            id: 10001
    on_success:
      return:
        issues@json: {{http_response.body}}
```

<kbd>![image](https://user-images.githubusercontent.com/63288/146831980-dc94bc96-0238-4c6c-9f10-d1bb918ad495.png)</kbd>
