### DISCUSSION TITLE
Trying to recreate old ticketing system interface

### DISCUSSION THREAD

**Discussion by ghost** [cerb/cerb-release#66] [Q&A]
Hello,

I am coming from Kayako. I do like the flexibility and customization of Cerb. But as a newbie, the amount of customization available in cerb is overwhelming. 

I am trying to recreate some interface of Kayako ticketing system. 

1. In Kayako raw of the specific ticket will change color according to the last ticket update. For example, it will turn red if the last update was a few hours ago or will turn to dark orange if the last update was one hour or above, etc. 

Currently, I am creating a separate widget for that. But is it possible to change the color of specific raw in data query results?

2. Change the size of pane in two pane layout dashboard. I can't find an option to change the size of each pane in two pane dashboard. The left pane is too large for me.

**Comment by beatbesmer** [comment]
If I'm not mistaken, concern 1 should be possible since version 10.4 at the latest. Provided you use a sheet to display the data. In it you could set the color of a row depending on a record field (e.g. updated).
See https://cerb.ai/releases/10.4/ ([Sheets] Sheet KATA may define optional column parameters for color: and text_color:)

**Comment by jstanden** [comment]
Hi @webofunni !

1. As @beatbesmer mentioned, a sheet widget is the way to go for colorizing text or cells/rows.

You can do something like this.

Data query:

```yaml
type:worklist.records
of:ticket
expand: [custom_,]
query:(
  status:o
  limit:15
  sort:[updated]
)
format:dictionaries
```

Sheet schema (KATA):

```yaml
layout:
  style: table
  headings@bool: yes
  paging@bool: yes
  colors:
    rainbow12@csv: #6e40aa, #b83cb0, #f6478d, #ff6956, #f59f30, #c4d93e, #83f557, #38f17a, #19d3b5, #29a0dd, #5069d9, #6e40aa

columns:
  card/_label:
    label: Ticket
    params:
      image@bool: yes
      bold@bool: yes
  card/group__label:
  text/delay:
    label: Last Update
    params:
      value_template@raw: {{('now'|date('U') - updated)|secs_pretty(1)}}
      color@raw:
        {% set secs = ('now'|date('U') - updated) %}
        {% if secs < 1800 %}rainbow12:0{% elseif secs < 3600 %}rainbow12:1{% endif %}
```

Alternatively you can use `text_color:` to just change the text color instead of the whole cell.

You can add the `color:` to all columns to highlight the entire row.

2. On dashboards you can use the 'open' (1 column) layout and set the widget widths manually (e.g. 25/75% or 50/50%). If you have an unusually large screen, you can also override the media stylesheet from Setup->Configure->Branding.
