### DISCUSSION TITLE
Automation - email.parse error message

### DISCUSSION THREAD

**Discussion by yungtyyler** [cerb/cerb-release#68] [Q&A] [answered]
Hey everyone,

I have been working in the interaction.website automation and have run across an interesting error message that I have not yet seen with the email.parse command:
<img width="332" alt="image" src="https://github.com/cerb/cerb-release/assets/115060069/d5c9e7af-4eff-48d5-8a8e-fb0bc3560a94">
I have about 8 other (situational) places in this automation that successfully run this command, but here is does not. I can't seem to find where the issue might be. Here is the snippet of code that is giving me this error:

```
record.search/participantSearch:
    output: results_workers
    inputs:
      record_type: worker
      record_query: email: {% if prompt_participants is empty %} Null {% else %} {{prompt_participants|replace({',': ' OR '})}} {% endif %}
    on_success:
      record.search/participantEmails:
        output: results_address
        inputs:
          record_type: address
          record_query: id: {{results_workers|map((worker) => worker.address_id)|join(',')|replace({',': ' OR id: '})}}
        on_error:
          await:
            form:
              title: Error
              elements:
                say/prompt_error:
                  content@text:
                    Something went wrong during results_address search!
        on_success:
          email.parse/emailMessage:
            output: email_message
            inputs:
              message@text:
                From: {{prompt_requesterEmail}}
                To: example@domain.com
                Subject: Employee Leaving Form - {{prompt_leavingEmployee}}
                
                An employee leaving form has been created for {{prompt_leavingEmployee}}.
                
                Employee: {{prompt_leavingEmployee}}
                Last Day: {{prompt_leaverLastDay|date('F d, Y')}}
                
                Email Forwarding:
                {% if prompt_leaverForwardEmails is empty %}
                N/A
                {% else %}
                {{prompt_leaverForwardEmails}}
                {% endif %}
                
                Request access to user account by:
                {% if prompt_leaverAccountAccess is empty %}
                N/A
                {% else %}
                {{prompt_leaverAccountAccess}}
                {% endif %}
                
                {% if prompt_leaverComment is empty%}
                N/A
                {% else %}
                Description:
                {{prompt_leaverComment}}
                {% endif %}
            on_success:
              record.update/new_ticket:
                output: new_ticket
                inputs:
                  record_type: ticket
                  record_id: {{email_message.id}}
                  fields:
                    subject: Employee Leaving Form - {{prompt_leavingEmployee}}
                    org_id: 3
                    group: PeopleChange
                    participants: {{prompt_participants|join(',')}}
                    links@list:
                      {%for worker in peopleChangeWorkers%}
                      worker: {{worker.id}}
                      {%endfor%}
                on_success:
                  await:
                    form:
                      elements:
                        say:
                          content@text:
                            Thank you for adding supplies for {{prompt_leavingEmployee}}!
                            
                            If you would like to request more supplies from other categories for {{prompt_leavingEmployee}} right now, click the gray **RESET** button.
                        submit:
                          continue@bool: no
                          reset@bool: yes
                on_error:
                  await:
                    form:
                      title: Error
                      elements:
                        say/prompt_error:
                          content@text:
                            Something went wrong with the ticket update!
```

Any advice would be greatly appreciated!
