### DISCUSSION TITLE
Support IP2Location.io API

### DISCUSSION THREAD

**Discussion by ip2location-com** [cerb/cerb-release#74] [Q&A]
IP2Location.io API could be a good alternative geolocation provider to provide users with more choices. It provides basic information such as country, region, city, latitude and longitude, ASN and AS, and WHOIS information for a domain.

User can sign up for a free API key to get started. User can perform 30,000 queries per month with a free API key.

For more information, you can check our documentation at [API documentation page](https://www.ip2location.io/ip2location-documentation). Hope you can consider adding this API as an option into your project.

**Comment by jstanden** [comment]
Cerb already integrates with any API that uses header/query keys, bearer tokens, OAuth1/OAuth2, AWS SIGV4, etc.

Nothing special would need to be done here.

**Comment by ip2location-com** [comment]
Hi @jstanden ,

Thank you for your response. We're looking to integrate our API with your software and have reviewed the documentation. However, we couldn't find instructions on submitting our plugin code. Could you guide us on this? Appreciate your help.

**Reply by jstanden** [reply]
Your docs show an API key for authentication.

In Cerb:

* Search >> Connected Services >> (+) >> Build

| Field | Value |
|---|---|
| Name: | ip2location
| URI: | ip2location
| Type: | API Key
| Base URL: | `https://api.ip2location.io/`
| API Key Name: | `key`
| API Key Location: | URL parameter

* Search >> Connected Accounts >> (+) >> ip2location

| Field | Value |
|---|---|
| Name: | ip2location
| URI: | ip2location
| API Key: | (paste from ip2location.io website)

* Search >> Automations >> (+) (e.g. `automation.function`)

```yaml
start:
  http.request/ip2location:
    output: http_response
    inputs:
      method: GET
      url: https://api.ip2location.io
      authentication: cerb:connected_account:ip2location
    on_success:
    on_error:
```
