### DISCUSSION TITLE
[mail.received] Rename inbound rfc822 email attachments from .txt to .eml

### DISCUSSION THREAD

**Discussion by jstanden** [cerb/cerb-release#75] [Automation Examples]
## mail.received

Automation:
```yaml
start:
  repeat:
    each@csv:
      {{
        message_attachments
          |filter((v) => v.file_name ends with '.txt' and v.file_type == 'message/rfc822')
          |keys
          |join(',')
      }}
    as: file_id
    do:
      record.update/rename:
        inputs:
          record_type: attachment
          record_id: {{file_id}}
          fields:
            name: {{message_attachments[file_id].file_name|replace({'.txt':'.eml'})}}
```

Policy:
```yaml
commands:
  record.update:
    deny/type@bool: {{inputs.record_type is not record type ('attachment')}}
    allow@bool: yes
```

Simulated Inputs:
```yaml
message__context: message
message_id: 1234
```
