### DISCUSSION TITLE
How to insert commands by default

### DISCUSSION THREAD

**Discussion by haldonclark** [cerb/cerb-release#76] [Q&A]
Hi,

I want to insert commands into the reply box by default like this

#original_message
#signature
#cut

so I don't have to do that manually every time.

When I enter this into the Email template, the text is being of these commands instead of the results of these commands.

**Comment by jstanden** [comment]
Hi @haldonclark!

You can use a `mail.draft` or `mail.send` automation to modify the default `#commands` on reply drafts. The former will modify the draft before the email editor opens. The latter will modify the sent message before it is delivered.

For instance, a `mail.draft` automation (**Search->Automations**):

```
start:
  return:
    draft:
      params:
        content: {{draft_params.content|replace({"#signature": "#original_message\r\n#signature"})}}
```

Then bind it in **Search->Automation Events->mail.draft**.

Every time you reply it will automatically add the `#original_message` command above `#signature`.
