### DISCUSSION TITLE
Cannot add a participant that contains "support" to tickets.

### DISCUSSION THREAD

**Discussion by j-at-se** [cerb/cerb-release#77] [Q&A] [answered]
Hello! My team has reported this issue today. I'm able to reproduce it consistently.

**Steps to reproduce:**

1. Go to a ticket

2. Click the Add Participants button in the widget(a)

3. Type `support@example.com` in the participant search field

4. Select `support@example.com` and click Continue

Expected result:

1. `support@example.com` is added to the participants for the ticket

Actual result:

1. `support@example.com` is not added to the participants for the ticket

Notes:

1. Other addresses can be added as participants; it seems that having "support" breaks this.
2. This isn't ticket-specific
3. The same happens when editing the ticket
4. The participant(s) already exist in Cerb

Thank you in advance for your help.

(a) The widget in question:
Data query:
```
type:worklist.records
of:addresses
expand:[]
query:(
  ticket.id:[{{record_id}}]
  sort:email
  limit: 5
)
format:dictionaries
```

Display this sheet schema:
```
layout:
  style: table
  headings@bool: no
  paging@bool: yes
  filtering@bool: yes

columns:
  selection/id:
  card/email:
    label: Email
    params:
      image@bool: yes
      bold@bool: yes
      context_key: _context
      label_key: _label
      id_key: id
```

Display this sheet toolbar:
```
interaction/add:
  label: Add participants
  uri: cerb:automation:cerb.ticket.participants.add
  inputs:
    ticket@key: record_id
  icon: circle-plus
  hidden@bool: 
    {% if row_selections is not empty %}yes{% endif %}
  after:
    refresh_widgets@bool: yes

interaction/remove:
  label: Remove {{row_selections|length}} selections
  uri: cerb:automation:cerb.ticket.participants.remove
  inputs:
    ticket@key: record_id 
    participants@key: row_selections 
  icon: circle-remove
  hidden@bool: 
    {% if row_selections is empty %}yes{% endif %}
  after:
    refresh_widgets@list:
      Participants

interaction/copy:
  label: Copy to clipboard
  uri: cerb:automation:cerb.interaction.echo
  icon: copy
  inputs:
    outputs:
      clipboard: {{record_participants|column('email')|join(', ')}}
      alert: Participants copied to clipboard.
```
