### DISCUSSION TITLE
Comments subordinated to comments: do they trigger a record.changed automation?

### DISCUSSION THREAD

**Discussion by j-at-se** [cerb/cerb-release#80] [Q&A]
Hi Cerb community!

**Context:**
I have a "preview" field for the purpose of showing an excerpt of the last message/comment on a ticket. This preview is displayed in the worklist:
![image](https://github.com/user-attachments/assets/f89c64a6-6fe0-433e-90e0-093503824551)

So far replies from both users and staff as well as top-level comments, are reflected in this field without issues.

However, when replying to a comment, this doesn't update the field:
![image](https://github.com/user-attachments/assets/ecaecaf5-7351-46ca-ba3b-f11e1c821345)

I believe that the "target" of a top-level comment is the ticket, but the replies to this comment have a different target: the original comment.

Is this correct?

Am I overthinking this and there's a simpler way to do this?

Here's my **record.changed** automation:
```
start:
  log: {{record__type}} :: {{change_type}}
  decision:
    outcome/message:
      if@bool: {{record__type == 'message' and change_type == 'created'}}
      then:
        record.update:
          inputs:
            record_type: ticket
            record_id: {{record_ticket_id}}
            fields:
              preview: {{record_content|strip_lines(prefixes='>')|truncate(128)}}

    outcome/comment:
      if@bool: {{record__type == 'comment'}}
      then:
        record.update:
          inputs:
            record_type: ticket
            record_id: {{record_target_id}}
            fields:
              preview: {{record_comment|truncate(128)}}
```

The policy:
```
commands:
  record.update:
    deny/type@bool: {{inputs.record_type is not record type ('ticket')}}
    allow@bool: yes
```
Thank you in advance for any insight on this.

Cheers!
