### DISCUSSION TITLE
Generate reply draft with LLM

### DISCUSSION THREAD

**Discussion by bolidesoft** [cerb/cerb-release#88] [Automation Examples]
Hi!

Huh, I messed in all these Bots, Behaviors, Automations, Triggers, Events, etc... Can someone explain to me how I can add a button to the "reply dialog", and when I click it, it passes the entire ticket contents with my own prompt to OpenAI API and inserts the reply as the draft reply? That will be a good starting point for me for further tuning.

Thanks!

**Comment by jstanden** [comment]
Hi @bolidesoft!

First, you can ignore bots and behaviors for anything new. They're replaced by automations.

With the earlier bot behaviors, they executed for their paired event immediately once created. That caused issues, since any changes you might be testing would also affect live events. It made reuse difficult, and was also inefficient since a behavior had to run to abort when it wasn't needed.

With automations, they don't execute unless they're "bound" to a trigger, like an event. You can conditionally bind to an event (e.g. for just one user, or specific records); which is more efficient since automations don't run when they aren't needed. As well, you can bind the same automation to an event multiple times with different conditions and inputs for reusability. One example would be an auto-reply automation that uses a different snippet depending on the group of a new ticket.

The [llm.agent](https://cerb.ai/docs/automations/commands/llm.agent/) automation command is best the way to interface with LLMs after Cerb [v11.1](https://cerb.ai/releases/11.1/) (which is in beta). To experiment with that early, you can pull the [v11.1-beta](https://github.com/cerb/cerb-release/tree/v11.1-beta) branch from GitHub, or use the [11.1](https://hub.docker.com/r/cerb/cerb) tag in Docker Hub.

In the current version and earlier, you can use the [http.request](https://cerb.ai/docs/automations/commands/http.request/) automation command and an [OpenAI](https://cerb.ai/solutions/integrations/openai/) connected account to use their [chatCompletions API](https://platform.openai.com/docs/api-reference/chat/create) directly.

Here's an example workflow you can import from **Search >> Workflows >> (+)**:

```yaml
workflow:
  name: example.mailRead.openaiDraft
  version: 2025-03-30T20:41:58Z
  requirements:
    cerb_version: >=11.0 <11.2
records:
  automation/scriptAiReply:
    fields:
      name: example.workerInteraction.openaiDraft
      extension_id: cerb.trigger.interaction.worker
      description@text:
      script@raw:
        inputs:
          record/message:
            record_type: message
            expand: ticket_requester_emails, sender_, content
            required@bool: yes
        
        start:
          await:
            duration:
              message: Generating...
              until: 1 second
          
          http.request/chatCompletion:
            output: http_response
            inputs:
              method: POST
              url: https://api.openai.com/v1/chat/completions
              authentication: cerb:connected_account:openai
              headers:
                Content-Type: application/json
              body:
                model: gpt-4o
                messages:
                  0:
                    role: developer
                    content@text:
                      You are a helpful helpdesk assistant who writes email drafts back to customers.
                      Just include the body of the message and not the subject.
                      Don't include a signature.
                      Use '> ' prefixes to quote relevant sections from the original message above your responses.
                  1:
                    role: user
                    content@text:
                      Write me an email reply draft for this original message:
                      
                      <email>
                      From: {{inputs.message.headers['from']}}
                      Subject : {{inputs.message.headers['subject']}}
                      
                      {{inputs.message.content}}
                      </email>
            on_success:
              set:
                api_response@json: {{http_response.body}}
              record.create/draft:
                output: draft_record
                inputs:
                  record_type: draft
                  fields:
                    type: ticket.reply
                    name: AI draft reply to {{inputs.message.sender__label}}
                    is_queued@int: 0
                    ticket_id@int: {{inputs.message.ticket_id}}
                    params:
                      to: {{inputs.message.ticket_requester_emails}}
                      subject: Re: {{inputs.message.ticket_subject}}
                      format: text
                      content@text:
                        {{api_response.choices[0].message.content}}
                        
                        
                        #signature
              return:
                alert: AI draft created!
      policy_kata@raw:
        commands:
          http.request:
            deny/url@bool: {{inputs.url is not prefixed ('https://api.openai.com/v1/')}}
            allow@bool: yes
          record.create:
            deny/type@bool: {{inputs.record_type is not record type ('draft')}}
            allow@bool: yes
  toolbar_section/toolbarMailRead:
    fields:
      name: AI Reply
      toolbar_name: mail.read
      priority@int: 1
      is_disabled: 0
      toolbar_kata@raw:
        interaction/aiDraft:
          label: AI Draft
          uri: cerb:automation:example.workerInteraction.openaiDraft
          icon: conversation
          hidden@bool: {{message_is_outgoing}}
          inputs:
            message: {{message_id}}
          after:
            refresh_widgets@csv: Conversation
```

Select **(Empty)**, paste the above template, then click **Continue** to the end.

Navigate to a ticket profile page and you'll see the following button on inbound messages:

![CleanShot 2025-03-30 at 13 44 03@2x](https://github.com/user-attachments/assets/8265d9ab-df26-4df5-ae8e-350dbad49609)

When you click the button, it will generate a resumable draft and add it to the conversation:

![CleanShot 2025-03-30 at 13 44 48@2x](https://github.com/user-attachments/assets/ff53ac87-00e8-48d1-b76a-2741719022f7)

You can also have the automation open the email editor popup with the draft directly.

In Cerb 11.1 using `llm.agent:` you can add [tools](https://cerb.ai/docs/automations/triggers/llm.tool/) to help generating the draft with your own help resources. For instance it can search your docs, FAQ, bug tracker, or knowledgebase to answer complex questions.

There's a short video preview of the new AI agent features here: https://www.youtube.com/shorts/74_6nQawnfk
