### DISCUSSION TITLE
Update attachments with known file extensions with the correct MIME type

### DISCUSSION THREAD

**Discussion by cohencor-m** [cerb/cerb-release#89] [Automation Examples]
If someone sends an attachment with a `.png`, `.jpg`, or `.gif` file type  as an `application/octet-stream`, this workflow will update it to the correct MIME type.

Workflow:

```
workflow:
  name: wgm.attachment.generic.fix
  version: 2025-03-31T23:22:10Z
  description: Fix generic attachments with known file extensions to use the proper MIME type
  website: https://cerb.ai/resources/workflows/
  requirements:
    cerb_version: >=11.0 <11.2
    cerb_plugins: cerberusweb.core, 
records:
  automation/genericAttachment:
    fields:
      name: wgm.attachment.mimefix
      extension_id: cerb.trigger.record.changed
      description: update the MIME type of known file extensions
      script@raw:
        start:
          decision/whatType:
            outcome/png:
              if@bool: {{record_name is suffixed ('.png')}}
              then:
                record.update/fix:
                  output: updated_attachment
                  inputs:
                    record_type: attachment
                    record_id: {{record_id}}
                    fields:
                      mime_type: image/png
            outcome/gif:
              if@bool: {{record_name is suffixed ('.gif')}}
              then:
                record.update/fix:
                  output: updated_attachment
                  inputs:
                    record_type: attachment
                    record_id: {{record_id}}
                    fields:
                      mime_type: image/gif
            outcome/jpg:
              if@bool: {{record_name is suffixed ('.jpg','jpeg')}}
              then:
                record.update/fix:
                  output: updated_attachment
                  inputs:
                    record_type: attachment
                    record_id: {{record_id}}
                    fields:
                      mime_type: image/jpeg
               
                
            
      policy_kata@raw:
        commands:
          record.update:
            deny/type@bool: {{inputs.record_type is not record type ('attachment')}}
            allow@bool: yes
  automation_event_listener/attachmentEvent:
    fields:
      name: Generic Attachment
      event_name: record.changed
      priority@int: 50
      is_disabled: 0
      event_kata@raw:
        automation/attachment:
          uri: cerb:automation:wgm.attachment.mimefix
          disabled@bool: 
            {{
              change_type not in ['created']
              or record__context is not record type ('attachment')
              or record_mime_type not in ['application/octet-stream']
            }}
```
