### DISCUSSION TITLE
Displaying and Downloading all files from a ticket at once

### DISCUSSION THREAD

**Discussion by Hildy** [cerb/cerb-release#90] [Automation Examples]
We've had occasional requests to be able to mass-download the attachments on an entire ticket thread.  This guide will walk you through creating an automation and a ticket profile widget to do just that.

<img width="316" alt="image" src="https://github.com/user-attachments/assets/d0800fa6-c51e-43ee-949b-b97cd2904ba8" />

First, we'll need to create an automation to process the attachments and present them to the worker.  Go to Search -> Automations and click the (+) to create a new one.  We'll call it `wgm.ticket.attachments.download`[1], give it whatever description you like, and for Trigger, select `interaction.worker`.

<img width="276" alt="image" src="https://github.com/user-attachments/assets/089d73a2-cf6b-416c-a49f-46273683b09f" />

[1] You can rename this if you like, but the name comes into play in the widget, so you'll have to update that, too

For the automation content, use:
```
inputs:
  record/ticket:
    record_type: ticket
    required@bool: yes
  records/attachments:
    record_type: attachment
    required@bool: yes

start:
  file.write:
    output: results
    inputs:
      name: {{inputs.ticket.mask}}_attachments.zip
      mime_type: application/zip
      expires@date: +15 mins
      content:
        zip:
          files@kata:
            {% for attachment in inputs.attachments %}
            file/{{attachment.id}}:
              path: {{attachment.id}}_{{attachment.name}}
              uri: cerb:attachment:{{attachment.id}}
            {% endfor %}
    #on_simulate:
    on_success:
      await:
        form:
          title: Download attachments for {{inputs.ticket.mask}}
          elements:
            fileDownload/prompt_file:
              label: {{inputs.ticket.mask}}_attachments.zip
              uri: {{results.uri}}
              filename: {{inputs.ticket.mask}}_attachments.zip
              
    #on_error:
```

On the Policy tab below, use:
```
commands:
  file.write:
    allow@bool: yes
```
<img width="187" alt="image" src="https://github.com/user-attachments/assets/7837ebde-d58e-4152-8b71-33f929c9b6ce" />

Save the automation you've created.

Next, go to a ticket profile page (any ticket), and click the "Add Widget" button: 
<img width="94" alt="image" src="https://github.com/user-attachments/assets/aff55aaf-80cc-48b3-b16a-dfa006bb5929" />

Select the Build tab, name it "Attachments", and select Type `Sheet`.

<img width="231" alt="image" src="https://github.com/user-attachments/assets/d5866c05-f66d-41f5-adef-a84b414edf17" />

For the Data Query, use:
```
type:worklist.records
of:attachment
query:(
  on.message:(ticket.id:{{record_id}}) name:!original_message.html
  limit:100
)
format:dictionaries
```

For the Sheet Schema, use:
```
layout:
  style: table
  headings: yes
  paging: yes
  #title_column: link

columns:
  selection/id:
  card/name:
    label: Name
    params:
      context_key: _context
      id_key: id
      label_key: _label
      image@bool: no
      bold@bool: no
      underline@bool: no

  date/created_:
    label: Created
    params:
      value_template@raw: {{updated}}
      
  text/size:
    label: Size
    params:
```

And for the Sheet Toolbar (this is where you'll have to update the automation name if you changed it), use:
```
interaction/download:
  label: Download {{row_selections|length}} attachment(s)
  uri: cerb:automation:wgm.ticket.attachments.download
  inputs:
    ticket@key: record_id
    attachments@key: row_selections 
  icon: cloud-download
  hidden@bool: 
    {% if row_selections is empty %}yes{% endif %}
  after:
    refresh_widgets@list:
      Ticket Attachments
```

Save this widget, and you'll now have a display showing every attachment on the ticket, and selecting them will allow you to download a zip file of the selected attachments.

**Comment by cohencor-m** [comment]
Alternatively, you can add this workflow to create both the automation and profile widget in a single step.

Navigate to Search > Workflows > (+) and choose Empty.

Paste the following in the box:

```
workflow:
  name: wgm.ticket.attachments.download
  version: 2025-04-06T00:04:46Z
  description: Display and easily download attachments on tickets
  website: https://cerb.ai/resources/workflows/
  requirements:
    cerb_version: >=11.0 <11.2
    cerb_plugins: cerberusweb.core, 
records:
  automation/download:
    fields:
      name: wgm.ticket.attachments.download
      extension_id: cerb.trigger.interaction.worker
      description: Download selected attachments
      script@raw:
        inputs:
          record/ticket:
            record_type: ticket
            required@bool: yes
          records/attachments:
            record_type: attachment
            required@bool: yes
        
        start:
          file.write:
            output: results
            inputs:
              name: {{inputs.ticket.mask}}_attachments.zip
              mime_type: application/zip
              expires@date: +15 mins
              content:
                zip:
                  files@kata:
                    {% for attachment in inputs.attachments %}
                    file/{{attachment.id}}:
                      path: {{attachment.id}}_{{attachment.name}}
                      uri: cerb:attachment:{{attachment.id}}
                    {% endfor %}
            #on_simulate:
            on_success:
              await:
                form:
                  title: Download attachments for {{inputs.ticket.mask}}
                  elements:
                    fileDownload/prompt_file:
                      label: {{inputs.ticket.mask}}_attachments.zip
                      uri: {{results.uri}}
                      filename: {{inputs.ticket.mask}}_attachments.zip
                      
            #on_error:
      policy_kata@raw:
        commands:
          file.write:
            allow@bool: yes
  profile_widget/sheet:
    fields:
      name: Attachments
      profile_tab_id: {{records.profile_tab_35.id}}
      extension_id: cerb.profile.tab.widget.sheet
      pos@int: 1
      width_units@int: 1
      zone@text:
      extension_params:
        data_query@raw:
          type:worklist.records
          of:attachment
          query:(
            on.message:(ticket.id:{{record_id}}) name:!original_message.html
            limit:100
          )
          format:dictionaries
        cache_secs@text:
        placeholder_simulator_kata@text:
        sheet_kata@raw:
          layout:
            style: table
            headings: yes
            paging: yes
            #title_column: link
          
          columns:
            selection/id:
            card/name:
              label: Name
              params:
                context_key: _context
                id_key: id
                label_key: _label
                image@bool: no
                bold@bool: no
                underline@bool: no
          
            date/created_:
              label: Created
              params:
                value_template@raw: {{updated}}
                
            text/size:
              label: Size
              params:
        toolbar_kata@raw:
          interaction/download:
            label: Download {{row_selections|length}} attachment(s)
            uri: cerb:automation:wgm.ticket.attachments.download
            inputs:
              ticket@key: record_id
              attachments@key: row_selections 
            icon: cloud-download
            hidden@bool: 
              {% if row_selections is empty %}yes{% endif %}
            after:
              refresh_widgets@list:
                Ticket Attachments
```
Click Continue and the whole thing should be up and ready to go.
